name: Deploy to production

on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: landing-page-staging-build
  ARTIFACT_PATH: dist/
  DEPLOY_PATH: www/

jobs:
  deploy:
    name: Deploy production environment
    runs-on: codeberg-tiny-lazy
    env:
      DEPLOY_HOST: ${{ secrets.FTP_HOST }}
      DEPLOY_USER: ${{ secrets.FTP_USER }}
      DEPLOY_PASS: ${{ secrets.FTP_PASS }}
    steps:
      # TODO: switch to download-artifact when forgejo/forgejo#8004 is fixed
      - name: Download build artifact
        id: download
        uses: actions/cache/restore@v5
        with:
          key: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: Checkout repo
        if: steps.download.outputs.cache-hit != 'true'
        uses: actions/checkout@v6

      - id: build
        if: steps.download.outputs.cache-hit != 'true'
        uses: ./.github/prepare
        with:
          artifact-name: ${{ env.ARTIFACT_NAME }}
          artifact-path: ${{ env.ARTIFACT_PATH }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq lftp
      - name: Deploy build artifact
        run: |
          lftp -u "$DEPLOY_USER,$DEPLOY_PASS" "$DEPLOY_HOST" <<CMD
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ftp:ssl-protect-list true;
            mirror --continue \
                   --dereference \
                   --reverse \
                   "$ARTIFACT_PATH" "$DEPLOY_PATH";
            exit
          CMD
