name: Deploy to production

on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: landing-page-staging-build
  DEPLOY_SOURCE: deploy/

jobs:
  deploy:
    name: Deploy production environment
    runs-on: codeberg-tiny-lazy
    env:
      DEPLOY_HOST: ${{ secrets.FTP_HOST }}
      DEPLOY_USER: ${{ secrets.FTP_USER }}
      DEPLOY_PASS: ${{ secrets.FTP_PASS }}
    steps:
      # TODO: switch to download-artifact when forgejo/forgejo#8004 is fixed
      - name: Download build artifact
        uses: actions/cache/restore@v5
        with:
          key: ${{ env.ARTIFACT_NAME }}
          fail-on-cache-miss: true
          path: ${{ env.DEPLOY_SOURCE }}
      - run: |
          curl --list-only \
               --pubkey "" \
               --silent -k \
               "sftp://$DEPLOY_USER:$DEPLOY_PASS@$DEPLOY_HOST"
