name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build landing page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 22.13.1
      - run: npm ci
      - run: npm run build
      - name: Upload build artifacts
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy landing page
        id: deploy
        uses: actions/deploy-pages@v4
