name: Lint check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 22.13.1

jobs:
  lint:
    name: Linting
    runs-on: codeberg-tiny

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run lint
